const buildMenu = (items, startPrice = 99, step = 20) =>
  items.map((name, index) => ({
    itemId: String(index + 1),
    name,
    price: startPrice + index * step,
  }));

const RESTAURANT_SEED = [
  {
    id: "101",
    name: "Spice Garden",
    cuisines: ["North Indian", "Biryani"],
    costForTwo: "Rs. 300 for two",
    avgRating: 4.3,
    sla: { deliveryTime: 30 },
    cloudinaryImageId: "spice_garden_img",
    startPrice: 159,
    menuItems: [
      "Chicken Biryani",
      "Paneer Butter Masala",
      "Butter Naan",
      "Veg Pulao",
      "Dal Makhani",
      "Tandoori Roti",
      "Chicken 65",
      "Gulab Jamun",
    ],
  },
  {
    id: "102",
    name: "Pizza Palace",
    cuisines: ["Italian", "Fast Food"],
    costForTwo: "Rs. 500 for two",
    avgRating: 4.5,
    sla: { deliveryTime: 25 },
    cloudinaryImageId: "pizza_palace_img",
    startPrice: 189,
    menuItems: [
      "Margherita Pizza",
      "Farmhouse Pizza",
      "Cheese Burst Pizza",
      "Paneer Tikka Pizza",
      "Garlic Bread",
      "Veg Supreme Pizza",
      "Chicken Pepperoni",
      "Choco Lava Cake",
    ],
  },
  {
    id: "103",
    name: "Burger Hub",
    cuisines: ["American", "Fast Food"],
    costForTwo: "Rs. 400 for two",
    avgRating: 4.2,
    sla: { deliveryTime: 20 },
    cloudinaryImageId: "burger_hub_img",
    startPrice: 99,
    menuItems: [
      "Veg Burger",
      "Chicken Burger",
      "Double Cheese Burger",
      "French Fries",
      "Loaded Fries",
      "Crispy Chicken",
      "Cold Coffee",
      "Chocolate Shake",
    ],
  },
  {
    id: "104",
    name: "Andhra Spice",
    cuisines: ["South Indian"],
    costForTwo: "Rs. 350 for two",
    avgRating: 4.4,
    sla: { deliveryTime: 35 },
    cloudinaryImageId: "andhra_spice_img",
    startPrice: 149,
    menuItems: [
      "Andhra Chicken Curry",
      "Gongura Mutton",
      "Steamed Rice",
      "Pappu",
      "Ragi Sangati",
      "Rayalaseema Chicken",
      "Curd Rice",
      "Boondi Laddu",
    ],
  },
  {
    id: "105",
    name: "Tandoori Nights",
    cuisines: ["North Indian", "Tandoor"],
    costForTwo: "Rs. 450 for two",
    avgRating: 4.1,
    sla: { deliveryTime: 40 },
    cloudinaryImageId: "tandoori_nights_img",
    startPrice: 179,
    menuItems: [
      "Tandoori Chicken",
      "Chicken Tikka",
      "Paneer Tikka",
      "Rumali Roti",
      "Butter Chicken",
      "Kadai Paneer",
      "Jeera Rice",
      "Malai Kulfi",
    ],
  },
  {
    id: "106",
    name: "Healthy Bowl",
    cuisines: ["Salads", "Healthy Food"],
    costForTwo: "Rs. 300 for two",
    avgRating: 4.6,
    sla: { deliveryTime: 18 },
    cloudinaryImageId: "healthy_bowl_img",
    startPrice: 139,
    menuItems: [
      "Greek Salad",
      "Protein Bowl",
      "Avocado Toast",
      "Quinoa Bowl",
      "Sprout Salad",
      "Fruit Bowl",
      "Smoothie",
      "Granola Yogurt",
    ],
  },
  {
    id: "107",
    name: "Chinese Wok",
    cuisines: ["Chinese"],
    costForTwo: "Rs. 350 for two",
    avgRating: 4.0,
    sla: { deliveryTime: 28 },
    cloudinaryImageId: "chinese_wok_img",
    startPrice: 129,
    menuItems: [
      "Veg Hakka Noodles",
      "Chicken Fried Rice",
      "Gobi Manchurian",
      "Chilli Paneer",
      "Hot and Sour Soup",
      "Schezwan Noodles",
      "Spring Rolls",
      "Honey Noodles",
    ],
  },
  {
    id: "108",
    name: "Biryani House",
    cuisines: ["Biryani"],
    costForTwo: "Rs. 400 for two",
    avgRating: 4.7,
    sla: { deliveryTime: 32 },
    cloudinaryImageId: "biryani_house_img",
    startPrice: 159,
    menuItems: [
      "Hyderabadi Biryani",
      "Egg Biryani",
      "Chicken Dum Biryani",
      "Veg Biryani",
      "Raita",
      "Mirchi Ka Salan",
      "Double Ka Meetha",
      "Haleem",
    ],
  },
  {
    id: "109",
    name: "Cafe Delight",
    cuisines: ["Cafe", "Desserts"],
    costForTwo: "Rs. 350 for two",
    avgRating: 4.3,
    sla: { deliveryTime: 22 },
    cloudinaryImageId: "cafe_delight_img",
    startPrice: 109,
    menuItems: [
      "Cold Coffee",
      "Brownie",
      "Pasta Alfredo",
      "Classic Sandwich",
      "Blueberry Cheesecake",
      "Veg Wrap",
      "Latte",
      "Muffin",
    ],
  },
  {
    id: "110",
    name: "Dosa Point",
    cuisines: ["South Indian"],
    costForTwo: "Rs. 250 for two",
    avgRating: 4.2,
    sla: { deliveryTime: 15 },
    cloudinaryImageId: "dosa_point_img",
    startPrice: 69,
    menuItems: [
      "Masala Dosa",
      "Idli Sambar",
      "Vada",
      "Mysore Dosa",
      "Onion Uttapam",
      "Pongal",
      "Filter Coffee",
      "Rava Dosa",
    ],
  },
  {
    id: "111",
    name: "Rolls Mania",
    cuisines: ["Rolls", "Fast Food"],
    costForTwo: "Rs. 300 for two",
    avgRating: 4.1,
    sla: { deliveryTime: 19 },
    cloudinaryImageId: "rolls_mania_img",
    startPrice: 99,
    menuItems: [
      "Chicken Roll",
      "Paneer Roll",
      "Egg Roll",
      "Veg Roll",
      "Double Egg Chicken Roll",
      "Mayo Fries",
      "Lemon Soda",
      "Chocolate Roll",
    ],
  },
  {
    id: "112",
    name: "Sweet Tooth",
    cuisines: ["Desserts"],
    costForTwo: "Rs. 200 for two",
    avgRating: 4.8,
    sla: { deliveryTime: 12 },
    cloudinaryImageId: "sweet_tooth_img",
    startPrice: 49,
    menuItems: [
      "Gulab Jamun",
      "Rasgulla",
      "Chocolate Cake",
      "Vanilla Pastry",
      "Falooda",
      "Fruit Custard",
      "Kaju Katli",
      "Rabdi",
    ],
  },
  {
    id: "113",
    name: "Grill Master",
    cuisines: ["BBQ", "Grill"],
    costForTwo: "Rs. 550 for two",
    avgRating: 4.5,
    sla: { deliveryTime: 38 },
    cloudinaryImageId: "grill_master_img",
    startPrice: 189,
    menuItems: [
      "Grilled Chicken",
      "BBQ Wings",
      "Peri Peri Fries",
      "Smoked Paneer",
      "Fish Fillet",
      "Mutton Chops",
      "Coleslaw",
      "Brownie Sundae",
    ],
  },
  {
    id: "114",
    name: "Veggie Delight",
    cuisines: ["Pure Veg"],
    costForTwo: "Rs. 300 for two",
    avgRating: 4.0,
    sla: { deliveryTime: 26 },
    cloudinaryImageId: "veggie_delight_img",
    startPrice: 89,
    menuItems: [
      "Veg Thali",
      "Dal Fry",
      "Jeera Rice",
      "Aloo Gobi",
      "Paneer Bhurji",
      "Chapati",
      "Curd",
      "Kheer",
    ],
  },
  {
    id: "115",
    name: "Street Chaat",
    cuisines: ["Chaat", "Snacks"],
    costForTwo: "Rs. 150 for two",
    avgRating: 4.3,
    sla: { deliveryTime: 14 },
    cloudinaryImageId: "street_chaat_img",
    startPrice: 30,
    menuItems: [
      "Pani Puri",
      "Bhel Puri",
      "Samosa",
      "Dahi Puri",
      "Sev Puri",
      "Pav Bhaji",
      "Vada Pav",
      "Jalebi",
    ],
  },
  {
    id: "116",
    name: "Kebab Junction",
    cuisines: ["Mughlai", "Kebab"],
    costForTwo: "Rs. 500 for two",
    avgRating: 4.4,
    sla: { deliveryTime: 34 },
    cloudinaryImageId: "kebab_junction_img",
    startPrice: 169,
    menuItems: [
      "Seekh Kebab",
      "Shami Kebab",
      "Malai Kebab",
      "Mutton Kebab",
      "Roomali Roti",
      "Mutton Biryani",
      "Mint Chutney",
      "Phirni",
    ],
  },
  {
    id: "117",
    name: "Pasta Street",
    cuisines: ["Italian"],
    costForTwo: "Rs. 420 for two",
    avgRating: 4.2,
    sla: { deliveryTime: 27 },
    cloudinaryImageId: "pasta_street_img",
    startPrice: 149,
    menuItems: [
      "Arrabiata Pasta",
      "Alfredo Pasta",
      "Pesto Pasta",
      "Bruschetta",
      "Cheese Garlic Bread",
      "Lasagna",
      "Iced Tea",
      "Tiramisu",
    ],
  },
  {
    id: "118",
    name: "Sushi Spot",
    cuisines: ["Japanese"],
    costForTwo: "Rs. 650 for two",
    avgRating: 4.6,
    sla: { deliveryTime: 36 },
    cloudinaryImageId: "sushi_spot_img",
    startPrice: 229,
    menuItems: [
      "Veg Sushi Roll",
      "Salmon Sushi",
      "Tempura Roll",
      "Miso Soup",
      "Teriyaki Bowl",
      "Edamame",
      "Ramen",
      "Mochi",
    ],
  },
  {
    id: "119",
    name: "Taco Town",
    cuisines: ["Mexican"],
    costForTwo: "Rs. 480 for two",
    avgRating: 4.3,
    sla: { deliveryTime: 29 },
    cloudinaryImageId: "taco_town_img",
    startPrice: 139,
    menuItems: [
      "Veg Taco",
      "Chicken Taco",
      "Nachos",
      "Burrito Bowl",
      "Quesadilla",
      "Mexican Rice",
      "Churros",
      "Lime Soda",
    ],
  },
  {
    id: "120",
    name: "Ramen House",
    cuisines: ["Asian", "Japanese"],
    costForTwo: "Rs. 520 for two",
    avgRating: 4.5,
    sla: { deliveryTime: 33 },
    cloudinaryImageId: "ramen_house_img",
    startPrice: 169,
    menuItems: [
      "Veg Ramen",
      "Chicken Ramen",
      "Spicy Miso Ramen",
      "Gyoza",
      "Katsu Curry",
      "Fried Rice",
      "Bubble Tea",
      "Matcha Cake",
    ],
  },
];

const SWIGGY_MENU_MOCK = RESTAURANT_SEED.map((restaurant) => ({
  id: restaurant.id,
  name: restaurant.name,
  cuisines: restaurant.cuisines,
  costForTwo: restaurant.costForTwo,
  avgRating: restaurant.avgRating,
  sla: restaurant.sla,
  cloudinaryImageId: restaurant.cloudinaryImageId,
  menu: buildMenu(restaurant.menuItems, restaurant.startPrice, 20),
}));

export default SWIGGY_MENU_MOCK;
